name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # linting job configuration and steps
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # only need to lint the latest version
        python-version: ["3.11"]

    steps:
      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python version ${{ matrix.python-version }}...
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: 3. Run the linters...
        uses: pre-commit/action@v3.0.0
